"""empty message

Revision ID: 1c603e2e088a
Revises: e34287736cb6
Create Date: 2023-09-06 19:50:48.950146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c603e2e088a'
down_revision = 'e34287736cb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.drop_constraint('bill_fk_customer_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.create_unique_constraint('bill_fk_customer_id_key', ['fk_customer_id'])

    # ### end Alembic commands ###
